Cu 86by51gnb create form unique to golden record
jembi/JeMPI pull request #235
Opened 2024-05-07 10:24 UTC by NyashaMuusha

### Description of changes
refactored generate id function
added unique to golden record data to table

### How to test
navigate to http://localhost:3001/settings
open the unique to golden record tab

### To check unit tests: 
npm run test

![Screenshot from 2024-05-07 12-15-58](https://github.com/jembi/JeMPI/assets/92095336/5b94a065-1b1d-438c-a441-83e8016b7b27)

2024-05-07 10:24 UTC, rcrichton commented
Task linked: [CU-86by1w64p JeMPI UI Configuration](https://app.clickup.com/t/86by1w64p)
Task linked: [CU-86by51gnb Create Form: Unique to Golden Record](https://app.clickup.com/t/86by51gnb)

2024-05-09 10:59 UTC, MatthewErispe requested changes

2024-05-09 10:59 UTC, MatthewErispe commented on JeMPI_Apps/JeMPI_UI/src/pages/settings/uniqueToGR/UniqueToGR.tsx
> +function EditToolbar(props: EditToolbarProps) {
@NyashaMuusha I notificed that this method is replicated in each tab. Can you refactor and extract this to a util that each tab can reference

2024-05-10 09:10 UTC, MatthewErispe commented on JeMPI_Apps/JeMPI_UI/src/pages/settings/uniqueToGR/UniqueToGR.tsx
> +function EditToolbar(props: EditToolbarProps) {
@NyashaMuusha I think this just needs to be replaced with the shared component

2024-05-10 10:35 UTC, merged