Cu 86by51hf7 create form unique to interaction
jembi/JeMPI pull request #236
Opened 2024-05-09 06:41 UTC by NyashaMuusha

![unique to interaction](https://github.com/jembi/JeMPI/assets/92095336/21183546-2553-4339-b7f4-c56f5e2d5ac8)

2024-05-09 06:41 UTC, rcrichton commented
Task linked: [CU-86by51hf7 Create Form: Unique to Interaction](https://app.clickup.com/t/86by51hf7)

2024-05-09 06:41 UTC, rcrichton commented
Task linked: [CU-86by1w64p JeMPI UI Configuration](https://app.clickup.com/t/86by1w64p)

2024-05-09 11:03 UTC, MatthewErispe requested changes

2024-05-09 11:03 UTC, MatthewErispe commented on JeMPI_Apps/JeMPI_UI/src/pages/settings/uniqueToInteraction/UniqueToInteraction.tsx
> +        const indexGoldenRecord = params.row.indexGoldenRecord
@NyashaMuusha Can you please refactor and extract this method to a hepler that performs this logic for all index fields in tabs

2024-05-09 11:04 UTC, MatthewErispe commented on JeMPI_Apps/JeMPI_UI/src/pages/settings/uniqueToInteraction/UniqueToInteraction.tsx
> +function EditToolbar(props: EditToolbarProps) {
@NyashaMuusha  Requested refactor in previous changes #235 . Please use the helper function once completed

2024-05-10 09:34 UTC, MatthewErispe approved these changes
@NyashaMuusha LGTM

2024-05-10 09:34 UTC, merged