Jmpi 66 fix import endpoint max file size
jembi/JeMPI pull request #31
Opened 2023-02-06 16:31 UTC by IlyesBenAmara

- This PR adds a max file size for the user to import to JeMPI

2023-02-06 17:18 UTC, marrouchi requested changes

2023-02-06 17:18 UTC, marrouchi commented on docker/conf/env/conf-env-1-pc.template
> +export FILE_IMPORT_MAX_SIZE=${FILE_IMPORT_MAX_SIZE}
```suggestion
export JEMPI_FILE_IMPORT_MAX_SIZE_BYTE=${JEMPI_FILE_IMPORT_MAX_SIZE_BYTE}
```
Let's prefix them all with "JEMPI_" et suffix them with "BYTE

2023-02-07 08:21 UTC, marrouchi approved these changes

2023-02-07 08:23 UTC, marrouchi reviewed
Might be good to add something about this endpoint in the documentation (documentation/api.md).

2023-02-07 08:24 UTC, IlyesBenAmara commented
@marrouchi Will do :technologist: :+1:

2023-02-07 09:27 UTC, MatthewErispe approved these changes
LGTM

2023-02-07 12:58 UTC, merged