Jmpi 174 flag candidates for review on recompute
jembi/JeMPI pull request #48
Opened 2023-03-13 07:09 UTC by ASomaroo

JMPI-174: flag for review with reason

2023-03-14 08:26 UTC, ASomaroo commented
Looking into the way errors are handled and propagated, we will probably add the error handling for the updateMatchingPatientRecordScoreForGoldenRecord flow to this commit.

2023-03-15 09:15 UTC, MatthewErispe reviewed
please see my comments

2023-03-16 08:30 UTC, marrouchi requested changes

2023-03-16 08:30 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/BackEnd.java
> +      float maxThreshold = AppConfig.BACK_END_MATCH_THRESHOLD + 0.1f;
How about we add "0.1f" in AppConfig as well ?

2023-03-16 08:30 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/BackEnd.java
> +                                     .map(candidate -> new WorkCandidate(candidate,
maybe we could chain a ".filter()" function after this to get candidates with scores within threshold and avoid having a "for" loop afterwards. Does it sound right/better ?

2023-03-16 08:30 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Linker/src/main/java/org/jembi/jempi/linker/BackEnd.java
> +   public static ArrayList<Notification.MatchData> getCandidates(final PatientRecord patientRecord) throws RuntimeException {
The function returns candidate match data notifications, so maybe we should use more appropriate name ? WDYT ?

2023-03-17 08:19 UTC, marrouchi approved these changes
👍

2023-03-17 08:36 UTC, merged