Jmpi 443 map json to fhir
jembi/JeMPI pull request #57
Opened 2023-04-03 12:59 UTC by IlyesBenAmara

2023-04-03 19:07 UTC, ajayyuvo commented
Hi,

Getting this screen after running through the installation instructions for Jembi/JeMPI and jembi/jempi-web.
All containers start successfully.
Last step that I run is ./deploy-platform-local.sh up local-frontend in the jembi/jempi-web project and the screenshot below is what I see. 
Not sure what should we be seeing after starting the front-end application.

Thank you,
Ajay Joshi 

> _ No description provided. _
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/123385508/229602084-8b8ddc13-9071-4803-b6ea-81e230e67c3f.png">

2023-04-07 14:09 UTC, marrouchi requested changes

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_API/pom.xml
> +        </dependency>
Do we need both ?

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/BackEnd.java
> +         patientJson = ctx.newJsonParser().setPrettyPrint(true).encodeResourceToString(patient);
Let's move them inside mapToPatientFhir() function

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_ETL/pom.xml
> +        </dependency>
fhir imported twice ? don't we need those deps only in the shared pakage ?

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_ETL/pom.xml
> +        </dependency>
Do we need those here ?

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_ETL/src/main/java/org/jembi/jempi/etl/JsonToFhir.java
> +import static org.apache.commons.text.WordUtils.capitalizeFully;
Let's not install a package for this, (remove)

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_ETL/src/main/java/org/jembi/jempi/etl/JsonToFhir.java
> +                return field.getString("fhirPath");
Let's optimize this ..

2023-04-07 14:09 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/pom.xml
> +        </dependency>
Do we need all three ?

2023-04-10 10:14 UTC, marrouchi approved these changes

2023-04-10 10:14 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/mapper/JsonToFhir.java
> +                } else if (fieldName.equals("patientId")) {
Aren't we treating this case in processField() ?

2023-04-10 10:16 UTC, marrouchi commented
@IlyesBenAmara  Looks good to me as an initial implementation for the fhir mapper. Note that we will need to add other fhir fields,  maybe we could achieve that as we go.

2023-04-14 11:12 UTC, MatthewErispe commented
Closing pull request. Duplicated by another

2023-04-14 11:12 UTC, closed without merging