Jmpi 496 fhir api query patient by
jembi/JeMPI pull request #62
Opened 2023-04-10 14:07 UTC by IlyesBenAmara

2023-04-11 13:42 UTC, marrouchi requested changes
We need to add a "link" attribute to the fhir resource response. More details about this here : https://www.notion.so/gicsandbox/MPI-interface-spec-9ec526af851342febdcfd16f9dc9a985

2023-04-11 13:42 UTC, marrouchi commented on JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
> +            LOGGER.error("nope");
Let's do human readable log messages 🙏

2023-04-11 13:45 UTC, marrouchi requested changes

2023-04-11 14:40 UTC, marrouchi requested changes

2023-04-11 14:40 UTC, marrouchi commented on JeMPI_Apps/JeMPI_API/src/main/java/org/jembi/jempi/api/HttpServer.java
> +                    path(segment(GlobalConstants.SEGMENT_FHIR).slash(segment(Pattern.compile("^[A-z0-9]+$"))),
Let's rather add a new route set in createRoutes() where the prefix is "fhir" instead of "JeMPI" line 973

2023-04-13 12:19 UTC, marrouchi requested changes

2023-04-13 12:19 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/mapper/JsonToFhir.java
> +                        patient.addLink().setOther(new Reference(String.format("Patient/%s", currPatient.patientRecord().patientId()))).setType(Patient.LinkType.SEEALSO);
Let's break this long line into multiple instructions.

2023-04-13 12:19 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/mapper/JsonToFhir.java
> +                    patient.addLink().setOther(new Reference(String.format("Patient/%s", goldenRecordWithScoreList.get(0).goldenRecord().goldenId()))).setType(Patient.LinkType.REFER);
Let's break this long line into multiple instructions.

2023-04-13 12:19 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/mapper/JsonToFhir.java
> +    public static String mapToPatientFhir(final String resourceId, final CustomDemographicData demographicData, final SourceId sourceId, final List<GoldenRecordWithScore> goldenRecordWithScoreList, f
Refactoring : I would recommend having 3 functions : 
- private mapRecordToFhirFormat
- public mapPatientRecordToFhirFormat
- public mapGoldenRecordToFhirFormat

both mapPatientRecordToFhirFormat() and mapGoldenRecordToFhirFormat() would call mapRecordToFhirFormat() to format demographic data.

2023-04-13 12:19 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/models/GlobalConstants.java
> +   public static final String SEGMENT_FHIR = "Patient";
```suggestion
   public static final String SEGMENT_FHIR_PATIENT = "Patient";
```

2023-04-13 12:19 UTC, marrouchi commented on JeMPI_Apps/JeMPI_Shared/src/main/java/org/jembi/jempi/shared/mapper/JsonToFhir.java
> +        String patientJson = ctx.newJsonParser().setPrettyPrint(true).encodeResourceToString(patient);
Let's break this into multiple lines.

2023-04-13 14:04 UTC, marrouchi approved these changes

2023-04-14 11:09 UTC, JeMPI-Kenya approved these changes
@IlyesBenAmara LGTM

2023-04-14 11:09 UTC, merged